### ISSUE TITLE
Support for Canvas Devices 

### ISSUE THREAD

**Issue by jaxcksn** [jaxcksn/nanoleafMusic#12]
Anything related to future support for Canvas Devices and all relevant updates/discussions will be posted here. If you have a canvas device and would like to help test canvas support I'd appreciate it as I don't own a canvas device.

**Comment by jaxcksn** [comment]
In https://github.com/jaxcksn/nanoleafMusic/commit/20e4d0ad1d52278dd812d172ae1ea921ee8fea57 on the dev branch, I replaced the Nanoleaf Aurora dependency with my own package I made specifically for this program. (It's very similar, but only with the features I need). 

This should make it easier to implement Canvas support.

**Comment by jaxcksn** [comment]
In https://github.com/jaxcksn/nanoleafMusic/commit/163282977a02278cb3ac175557d24e4044808866 I added two built release binaries for Canvas support if you would like to test. They should work in theory, but I have no way to test if it does:

For Windows: [Download Here](https://github.com/jaxcksn/nanoleafMusic/raw/canvas-support/assets/beta-releases/NanoleafMusic-1.2-beta.msi)
For macOS: [Download Here](https://github.com/jaxcksn/nanoleafMusic/raw/canvas-support/assets/beta-releases/nanoleafMusic-1.2-beta.dmg)

**Comment by ProfessoRJ13** [comment]
> In [1632829](https://github.com/jaxcksn/nanoleafMusic/commit/163282977a02278cb3ac175557d24e4044808866) I added two built release binaries for Canvas support if you would like to test. They should work in theory, but I have no way to test if it does:
> 
> For Windows: [Download Here](https://github.com/jaxcksn/nanoleafMusic/raw/canvas-support/assets/beta-releases/NanoleafMusic-1.2-beta.msi)
> For macOS: [Download Here](https://github.com/jaxcksn/nanoleafMusic/raw/canvas-support/assets/beta-releases/nanoleafMusic-1.2-beta.dmg)

Tested - works perfectly as far as I can tell!
One thing which I don't know if it's supposed to happen is that after the first setup of my canvas panels - which showed up immediatly in the device selection - and I saved as a reconnect, and then after closing the software, it wouldn't show up again in the selection window. Is this a bug or due to it already being saved as the reconnect it doesnt put it in available connections? Reconnecting worked fine!
Edit: Tested on windows, will test on mac shortly
Edit 2: Turns out that when reconnecting, it doesnt reconnect properly. I needed to press and hold power to open device connections after pressing reconnect, even when the software said it was connected successfully, otherwise it didnt show any lighting effects. Not sure if there's a way around this, but maybe an updated popup/instructions saying to do that, or listed in troubleshooting would work.

**Comment by jaxcksn** [comment]
> Edit 2: Turns out that when reconnecting, it doesnt reconnect properly. I needed to press and hold power to open device connections after pressing reconnect, even when the software said it was connected successfully, otherwise it didnt show any lighting effects. Not sure if there's a way around this, but maybe an updated popup/instructions saying to do that, or listed in troubleshooting would work.

This is definitely a bug. I'll create an issue for it and work on it when I get the chance. It'll be patched before version 1.2 is realized.

I appreciate your help!

**Comment by ProfessoRJ13** [comment]
> > Edit 2: Turns out that when reconnecting, it doesnt reconnect properly. I needed to press and hold power to open device connections after pressing reconnect, even when the software said it was connected successfully, otherwise it didnt show any lighting effects. Not sure if there's a way around this, but maybe an updated popup/instructions saying to do that, or listed in troubleshooting would work.
> 
> This is definitely a bug. I'll create an issue for it and work on it when I get the chance. It'll be patched before version 1.2 is realized.
> 
> I appreciate your help!

Just tested on mac, the bug is not present there, reconnecting works like a dream.
The other thing I noticed on Windows in relation to the bug where it stops playing anything is that it happened pretty regularly as a song finished - it wouldnt play lights for the next song until I reloaded effects. Again, doesn't seem to happen on mac.
